# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import experian_prequal
from experian_prequal.paths.v1_credit_score import post  # noqa: E501
from experian_prequal import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1CreditScore(ApiTestMixin, unittest.TestCase):
    """
    V1CreditScore unit test stubs
        Prequalification Credit Score  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
