# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

import unittest

import experian_prequal
from experian_prequal.model.public_record_resp import PublicRecordResp
from experian_prequal import configuration


class TestPublicRecordResp(unittest.TestCase):
    """PublicRecordResp unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
