# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class ClarityAccountData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            clarityAccountId = schemas.StrSchema
            clarityLocationId = schemas.StrSchema
            clarityControlFileName = schemas.StrSchema
            clarityControlFileVersion = schemas.StrSchema
            clarityAttributesControlFileName = schemas.StrSchema
            __annotations__ = {
                "clarityAccountId": clarityAccountId,
                "clarityLocationId": clarityLocationId,
                "clarityControlFileName": clarityControlFileName,
                "clarityControlFileVersion": clarityControlFileVersion,
                "clarityAttributesControlFileName": clarityAttributesControlFileName,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clarityAccountId"]) -> MetaOapg.properties.clarityAccountId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clarityLocationId"]) -> MetaOapg.properties.clarityLocationId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clarityControlFileName"]) -> MetaOapg.properties.clarityControlFileName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clarityControlFileVersion"]) -> MetaOapg.properties.clarityControlFileVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clarityAttributesControlFileName"]) -> MetaOapg.properties.clarityAttributesControlFileName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["clarityAccountId", "clarityLocationId", "clarityControlFileName", "clarityControlFileVersion", "clarityAttributesControlFileName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clarityAccountId"]) -> typing.Union[MetaOapg.properties.clarityAccountId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clarityLocationId"]) -> typing.Union[MetaOapg.properties.clarityLocationId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clarityControlFileName"]) -> typing.Union[MetaOapg.properties.clarityControlFileName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clarityControlFileVersion"]) -> typing.Union[MetaOapg.properties.clarityControlFileVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clarityAttributesControlFileName"]) -> typing.Union[MetaOapg.properties.clarityAttributesControlFileName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["clarityAccountId", "clarityLocationId", "clarityControlFileName", "clarityControlFileVersion", "clarityAttributesControlFileName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        clarityAccountId: typing.Union[MetaOapg.properties.clarityAccountId, str, schemas.Unset] = schemas.unset,
        clarityLocationId: typing.Union[MetaOapg.properties.clarityLocationId, str, schemas.Unset] = schemas.unset,
        clarityControlFileName: typing.Union[MetaOapg.properties.clarityControlFileName, str, schemas.Unset] = schemas.unset,
        clarityControlFileVersion: typing.Union[MetaOapg.properties.clarityControlFileVersion, str, schemas.Unset] = schemas.unset,
        clarityAttributesControlFileName: typing.Union[MetaOapg.properties.clarityAttributesControlFileName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ClarityAccountData':
        return super().__new__(
            cls,
            *args,
            clarityAccountId=clarityAccountId,
            clarityLocationId=clarityLocationId,
            clarityControlFileName=clarityControlFileName,
            clarityControlFileVersion=clarityControlFileVersion,
            clarityAttributesControlFileName=clarityAttributesControlFileName,
            _configuration=_configuration,
            **kwargs,
        )
