# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class ConsumerIdentity(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def name() -> typing.Type['ConsumerIdentityName']:
                return ConsumerIdentityName
        
            @staticmethod
            def phone() -> typing.Type['ConsumerIdentityPhone']:
                return ConsumerIdentityPhone
        
            @staticmethod
            def dob() -> typing.Type['ConsumerIdentityDob']:
                return ConsumerIdentityDob
            __annotations__ = {
                "name": name,
                "phone": phone,
                "dob": dob,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'ConsumerIdentityName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> 'ConsumerIdentityPhone': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dob"]) -> 'ConsumerIdentityDob': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "phone", "dob", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union['ConsumerIdentityName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> typing.Union['ConsumerIdentityPhone', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dob"]) -> typing.Union['ConsumerIdentityDob', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "phone", "dob", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union['ConsumerIdentityName', schemas.Unset] = schemas.unset,
        phone: typing.Union['ConsumerIdentityPhone', schemas.Unset] = schemas.unset,
        dob: typing.Union['ConsumerIdentityDob', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConsumerIdentity':
        return super().__new__(
            cls,
            *args,
            name=name,
            phone=phone,
            dob=dob,
            _configuration=_configuration,
            **kwargs,
        )

from experian_prequal.model.consumer_identity_dob import ConsumerIdentityDob
from experian_prequal.model.consumer_identity_name import ConsumerIdentityName
from experian_prequal.model.consumer_identity_phone import ConsumerIdentityPhone
