# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class ConsumerIdentifierCheckOptions(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Output a 17 byte unique consumer identifier for requestor and/or verify an input 17 byte unique consumer identifier.
    """


    class MetaOapg:
        
        class properties:
            getUniqueConsumerIdentifier = schemas.StrSchema
            verifyPrimaryConsumerIdentifier = schemas.StrSchema
            verifySecondaryConsumerIdentifier = schemas.StrSchema
            __annotations__ = {
                "getUniqueConsumerIdentifier": getUniqueConsumerIdentifier,
                "verifyPrimaryConsumerIdentifier": verifyPrimaryConsumerIdentifier,
                "verifySecondaryConsumerIdentifier": verifySecondaryConsumerIdentifier,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["getUniqueConsumerIdentifier"]) -> MetaOapg.properties.getUniqueConsumerIdentifier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["verifyPrimaryConsumerIdentifier"]) -> MetaOapg.properties.verifyPrimaryConsumerIdentifier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["verifySecondaryConsumerIdentifier"]) -> MetaOapg.properties.verifySecondaryConsumerIdentifier: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["getUniqueConsumerIdentifier", "verifyPrimaryConsumerIdentifier", "verifySecondaryConsumerIdentifier", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["getUniqueConsumerIdentifier"]) -> typing.Union[MetaOapg.properties.getUniqueConsumerIdentifier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["verifyPrimaryConsumerIdentifier"]) -> typing.Union[MetaOapg.properties.verifyPrimaryConsumerIdentifier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["verifySecondaryConsumerIdentifier"]) -> typing.Union[MetaOapg.properties.verifySecondaryConsumerIdentifier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["getUniqueConsumerIdentifier", "verifyPrimaryConsumerIdentifier", "verifySecondaryConsumerIdentifier", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        getUniqueConsumerIdentifier: typing.Union[MetaOapg.properties.getUniqueConsumerIdentifier, str, schemas.Unset] = schemas.unset,
        verifyPrimaryConsumerIdentifier: typing.Union[MetaOapg.properties.verifyPrimaryConsumerIdentifier, str, schemas.Unset] = schemas.unset,
        verifySecondaryConsumerIdentifier: typing.Union[MetaOapg.properties.verifySecondaryConsumerIdentifier, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConsumerIdentifierCheckOptions':
        return super().__new__(
            cls,
            *args,
            getUniqueConsumerIdentifier=getUniqueConsumerIdentifier,
            verifyPrimaryConsumerIdentifier=verifyPrimaryConsumerIdentifier,
            verifySecondaryConsumerIdentifier=verifySecondaryConsumerIdentifier,
            _configuration=_configuration,
            **kwargs,
        )
