# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class DirectCheck(
    schemas.ListSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Subscriber Information of subscriber codes shown on credit profile. Present when direct check is requested on input or via subcode option.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['DirectCheckResp']:
            return DirectCheckResp

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['DirectCheckResp'], typing.List['DirectCheckResp']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DirectCheck':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'DirectCheckResp':
        return super().__getitem__(i)

from experian_prequal.model.direct_check_resp import DirectCheckResp
