# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class Employment(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Consumer's Employment Details
    """


    class MetaOapg:
        required = {
            "employerName",
        }
        
        class properties:
            employerName = schemas.StrSchema
        
            @staticmethod
            def employerAddress() -> typing.Type['Address']:
                return Address
            __annotations__ = {
                "employerName": employerName,
                "employerAddress": employerAddress,
            }
    
    employerName: MetaOapg.properties.employerName
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employerName"]) -> MetaOapg.properties.employerName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employerAddress"]) -> 'Address': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employerName", "employerAddress", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employerName"]) -> MetaOapg.properties.employerName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employerAddress"]) -> typing.Union['Address', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employerName", "employerAddress", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employerName: typing.Union[MetaOapg.properties.employerName, str, ],
        employerAddress: typing.Union['Address', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Employment':
        return super().__new__(
            cls,
            *args,
            employerName=employerName,
            employerAddress=employerAddress,
            _configuration=_configuration,
            **kwargs,
        )

from experian_prequal.model.address import Address
