# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class MlaResp(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Present when "mla" is requested on input or via subcode and is allowed for the subcode.
    """


    class MetaOapg:
        
        class properties:
            messageNumber = schemas.StrSchema
            messageText = schemas.StrSchema
            __annotations__ = {
                "messageNumber": messageNumber,
                "messageText": messageText,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["messageNumber"]) -> MetaOapg.properties.messageNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["messageText"]) -> MetaOapg.properties.messageText: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["messageNumber", "messageText", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["messageNumber"]) -> typing.Union[MetaOapg.properties.messageNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["messageText"]) -> typing.Union[MetaOapg.properties.messageText, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["messageNumber", "messageText", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        messageNumber: typing.Union[MetaOapg.properties.messageNumber, str, schemas.Unset] = schemas.unset,
        messageText: typing.Union[MetaOapg.properties.messageText, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MlaResp':
        return super().__new__(
            cls,
            *args,
            messageNumber=messageNumber,
            messageText=messageText,
            _configuration=_configuration,
            **kwargs,
        )
