# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class ModelAttributesResp1(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            modelTypeIndicator = schemas.StrSchema
            variableName = schemas.StrSchema
            signofAttribute = schemas.StrSchema
            attributeValue = schemas.StrSchema
            __annotations__ = {
                "modelTypeIndicator": modelTypeIndicator,
                "variableName": variableName,
                "signofAttribute": signofAttribute,
                "attributeValue": attributeValue,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modelTypeIndicator"]) -> MetaOapg.properties.modelTypeIndicator: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variableName"]) -> MetaOapg.properties.variableName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["signofAttribute"]) -> MetaOapg.properties.signofAttribute: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attributeValue"]) -> MetaOapg.properties.attributeValue: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["modelTypeIndicator", "variableName", "signofAttribute", "attributeValue", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modelTypeIndicator"]) -> typing.Union[MetaOapg.properties.modelTypeIndicator, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variableName"]) -> typing.Union[MetaOapg.properties.variableName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["signofAttribute"]) -> typing.Union[MetaOapg.properties.signofAttribute, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attributeValue"]) -> typing.Union[MetaOapg.properties.attributeValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["modelTypeIndicator", "variableName", "signofAttribute", "attributeValue", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        modelTypeIndicator: typing.Union[MetaOapg.properties.modelTypeIndicator, str, schemas.Unset] = schemas.unset,
        variableName: typing.Union[MetaOapg.properties.variableName, str, schemas.Unset] = schemas.unset,
        signofAttribute: typing.Union[MetaOapg.properties.signofAttribute, str, schemas.Unset] = schemas.unset,
        attributeValue: typing.Union[MetaOapg.properties.attributeValue, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ModelAttributesResp1':
        return super().__new__(
            cls,
            *args,
            modelTypeIndicator=modelTypeIndicator,
            variableName=variableName,
            signofAttribute=signofAttribute,
            attributeValue=attributeValue,
            _configuration=_configuration,
            **kwargs,
        )
