# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class PII(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Personally Identifiable Information
    """


    class MetaOapg:
        required = {
            "primaryApplicant",
        }
        
        class properties:
        
            @staticmethod
            def primaryApplicant() -> typing.Type['PrimaryApplicant']:
                return PrimaryApplicant
        
            @staticmethod
            def secondaryApplicant() -> typing.Type['SecondaryApplicant']:
                return SecondaryApplicant
            __annotations__ = {
                "primaryApplicant": primaryApplicant,
                "secondaryApplicant": secondaryApplicant,
            }
    
    primaryApplicant: 'PrimaryApplicant'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["primaryApplicant"]) -> 'PrimaryApplicant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secondaryApplicant"]) -> 'SecondaryApplicant': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["primaryApplicant", "secondaryApplicant", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["primaryApplicant"]) -> 'PrimaryApplicant': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secondaryApplicant"]) -> typing.Union['SecondaryApplicant', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["primaryApplicant", "secondaryApplicant", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        primaryApplicant: 'PrimaryApplicant',
        secondaryApplicant: typing.Union['SecondaryApplicant', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PII':
        return super().__new__(
            cls,
            *args,
            primaryApplicant=primaryApplicant,
            secondaryApplicant=secondaryApplicant,
            _configuration=_configuration,
            **kwargs,
        )

from experian_prequal.model.primary_applicant import PrimaryApplicant
from experian_prequal.model.secondary_applicant import SecondaryApplicant
