# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class PrequalScoreResp(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def informationalMessage() -> typing.Type['InformationalMessage']:
                return InformationalMessage
        
            @staticmethod
            def riskModel() -> typing.Type['RiskModel']:
                return RiskModel
        
            @staticmethod
            def statement() -> typing.Type['Statement']:
                return Statement
            __annotations__ = {
                "informationalMessage": informationalMessage,
                "riskModel": riskModel,
                "statement": statement,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["informationalMessage"]) -> 'InformationalMessage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["riskModel"]) -> 'RiskModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["statement"]) -> 'Statement': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["informationalMessage", "riskModel", "statement", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["informationalMessage"]) -> typing.Union['InformationalMessage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["riskModel"]) -> typing.Union['RiskModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["statement"]) -> typing.Union['Statement', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["informationalMessage", "riskModel", "statement", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        informationalMessage: typing.Union['InformationalMessage', schemas.Unset] = schemas.unset,
        riskModel: typing.Union['RiskModel', schemas.Unset] = schemas.unset,
        statement: typing.Union['Statement', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PrequalScoreResp':
        return super().__new__(
            cls,
            *args,
            informationalMessage=informationalMessage,
            riskModel=riskModel,
            statement=statement,
            _configuration=_configuration,
            **kwargs,
        )

from experian_prequal.model.informational_message import InformationalMessage
from experian_prequal.model.risk_model import RiskModel
from experian_prequal.model.statement import Statement
