# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class RentBureauAccountData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            primaryApplRentBureauFreezePin = schemas.StrSchema
            secondaryApplRentBureauFreezePin = schemas.StrSchema
            __annotations__ = {
                "primaryApplRentBureauFreezePin": primaryApplRentBureauFreezePin,
                "secondaryApplRentBureauFreezePin": secondaryApplRentBureauFreezePin,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["primaryApplRentBureauFreezePin"]) -> MetaOapg.properties.primaryApplRentBureauFreezePin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secondaryApplRentBureauFreezePin"]) -> MetaOapg.properties.secondaryApplRentBureauFreezePin: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["primaryApplRentBureauFreezePin", "secondaryApplRentBureauFreezePin", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["primaryApplRentBureauFreezePin"]) -> typing.Union[MetaOapg.properties.primaryApplRentBureauFreezePin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secondaryApplRentBureauFreezePin"]) -> typing.Union[MetaOapg.properties.secondaryApplRentBureauFreezePin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["primaryApplRentBureauFreezePin", "secondaryApplRentBureauFreezePin", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        primaryApplRentBureauFreezePin: typing.Union[MetaOapg.properties.primaryApplRentBureauFreezePin, str, schemas.Unset] = schemas.unset,
        secondaryApplRentBureauFreezePin: typing.Union[MetaOapg.properties.secondaryApplRentBureauFreezePin, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RentBureauAccountData':
        return super().__new__(
            cls,
            *args,
            primaryApplRentBureauFreezePin=primaryApplRentBureauFreezePin,
            secondaryApplRentBureauFreezePin=secondaryApplRentBureauFreezePin,
            _configuration=_configuration,
            **kwargs,
        )
