# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from experian_prequal import schemas  # noqa: F401


class VendorData(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Optional field. To understand who's application the client is using to send in the inquiry - Vendor, 3rd Party, Reseller, or client home grown.
    """


    class MetaOapg:
        
        class properties:
            vendorNumber = schemas.StrSchema
            vendorVersion = schemas.StrSchema
            __annotations__ = {
                "vendorNumber": vendorNumber,
                "vendorVersion": vendorVersion,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendorNumber"]) -> MetaOapg.properties.vendorNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vendorVersion"]) -> MetaOapg.properties.vendorVersion: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["vendorNumber", "vendorVersion", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendorNumber"]) -> typing.Union[MetaOapg.properties.vendorNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vendorVersion"]) -> typing.Union[MetaOapg.properties.vendorVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["vendorNumber", "vendorVersion", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        vendorNumber: typing.Union[MetaOapg.properties.vendorNumber, str, schemas.Unset] = schemas.unset,
        vendorVersion: typing.Union[MetaOapg.properties.vendorVersion, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VendorData':
        return super().__new__(
            cls,
            *args,
            vendorNumber=vendorNumber,
            vendorVersion=vendorVersion,
            _configuration=_configuration,
            **kwargs,
        )
