# coding: utf-8

"""
    Prequalification Credit Report

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: OpenAPI3.1.0.12
    Generated by: https://openapi-generator.tech
"""

from experian_prequal.paths.v1_credit_report.post import CreditReport
from experian_prequal.paths.v1_credit_score.post import CreditScore


class ConsumerServicesApi(
    CreditReport,
    CreditScore,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
